name: APK-J Build

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Clone Project
        run: git clone -b main --depth=1 https://github.com/q215613905/TVBoxOS.git

      - name: DIY Script
        run: |
          chmod +x diy-J.sh
          bash ${{ github.workspace }}/diy-J.sh

      - name: Build With Gradle
        run: |
          num=$(find ${{ github.workspace }} -name gradlew | awk -F"/" '{print NF-1}')
          DIR=$(find ${{ github.workspace }} -name gradlew | cut -d \/ -f$num)
          cd "$DIR"
          chmod +x gradlew
          ./gradlew assembleRelease --build-cache --parallel --daemon --warning-mode all

      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          find ~ -name "*.apk" -exec mv {} ${{ github.workspace }}/apk/ \;

      - uses: actions/upload-artifact@v4.6.1
        with:
          name: com.github.tvbox.osc
          path: ${{ github.workspace }}/apk/*
